### PR TITLE
Upgrade debug to latest

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by popomore** [comment]
I don't know CI failed, I have tested under iojs, can you retry it?

**Comment by JacksonTian** [comment]
测试重试跑过了。问题是升级debug的版本带来的收益是？

**Comment by popomore** [comment]
This feature https://github.com/visionmedia/debug/commit/e4d021a2232a7df472715e16e81d758131033774

**Comment by JacksonTian** [comment]
好。

**Comment by JacksonTian** [comment]
`+ eventproxy@0.3.3`

**Comment by fengmk2** [comment]
+1

**Pull request merged**
